version: '3'

networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo/forgejo:8
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
    restart: always
    networks:
      - forgejo
    volumes:
      - ./git:/var/lib/forgejo/git
#     - ./forgejo:/data
      - ./forgejo:/var/lib/forgejo
      - ./etc/forgejo:/etc/forgejo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '222:22'
# no database defined -> default sqlite
#    depends_on:
#      - db
#
#  db:
#    image: postgres:14
#    restart: always
#    environment:
#      - POSTGRES_USER=forgejo
#      - POSTGRES_PASSWORD=forgejo
#      - POSTGRES_DB=forgejo
#    networks:
#      - forgejo
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
