version: "3.9"
name: "forgejo"

networks:
  forgejo-net:
    driver: bridge
    external: false

volumes:
  data-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
    device: ./data
  db-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
    device: ./data/forgejo.db
  git-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
    device: ./git
  config-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
    device: ./app.ini
    
services:
  server:
    image: codeberg.org/forgejo/forgejo:8-rootless
    container_name: forgejo
    restart: on-failure:3
    read_only: "true"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=sqlite3
    networks:
      - forgejo-net
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:222:22"
    volumes:
      - git-vol:/var/lib/gitea/git
      - data-vol:/var/lib/gitea/data
      - db-vol:/var/lib/gitea/data/forgejo.db
      - config-vol:/etc/gitea/app.ini:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
