version: "3"

name: forgejo

networks:
  forgejo-net:
    external: false

volumes:
  forgejo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
    device: /container/forgejo/data
  forgejo-git:
    external: true
  log:
  tmp:

services:
  server:
    image: codeberg.org/forgejo/forgejo:8-rootless
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=sqlite3
#      - FORGEJO__database__HOST=db:5432
#      - FORGEJO__database__NAME=forgejo
#      - FORGEJO__database__USER=forgejo
#      - FORGEJO__database__PASSWD=forgejo
    restart: always
    networks:
      - forgejo-net
    volumes:
      - ./git:/var/lib/forgejo/git
      - data:/data/forgejo.db
#      - ./forgejo:/var/lib/forgejo
#      - ./etc/forgejo:/etc/forgejo:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:222:22"
# no database defined -> default sqlite
#    depends_on:
#      - db
#
#  db:
#    image: postgres:14
#    restart: always
#    environment:
#      - POSTGRES_USER=forgejo
#      - POSTGRES_PASSWORD=forgejo
#      - POSTGRES_DB=forgejo
#    networks:
#      - forgejo
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
